### ISSUE TITLE
Can't build the test project

### ISSUE THREAD

**Issue by DavidBarishev** [leye0/XamarinAndroidFFmpeg#3]
Hello!
I Hope this repository isn't dead, it's really usefull. I have cloned it and tried to build the test's project, but without any success.The only thing i changed the target API version to 19. 

Here is the error i couldn't resolve : 

```
Error       The "CheckDuplicateJavaLibraries" task failed unexpectedly.
System.IO.FileNotFoundException: Could not find file 'D:\Program Files\Android\android-sdk\extras\android\support\multidex\library\libs\android-support-multidex.jar'.
File name: 'D:\Program Files\Android\android-sdk\extras\android\support\multidex\library\libs\android-support-multidex.jar'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileInfo.get_Length()
   at Xamarin.Android.Tasks.MonoAndroidHelper.SizeAndContentFileComparer.GetHashCode(FileInfo obj)
   at System.Linq.Set`1.InternalGetHashCode(TElement value)
   at System.Linq.Set`1.Find(TElement value, Boolean add)
   at System.Linq.Enumerable.<DistinctIterator>d__63`1.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Xamarin.Android.Tasks.MonoAndroidHelper.DistinctFilesByContent(IEnumerable`1 filePaths)
   at Xamarin.Android.Tasks.CheckDuplicateJavaLibraries.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext() XamarinAndroidFFmpegTests           
```

Any idea ? My other xamarin project are building fine.

**Comment by leye0** [comment]
Android SDK Manager -> Packages -> Show Obsolete Packages -> Extras –> Android Support Library
